module Day19

using ..Utils

struct Rule
    id::Int
    subrules::Vector{Vector{Int}}
    char::Union{Nothing, Char}
end


function day19(; part::Int=2, example::Bool=false)
    lines = read_lines(19; example)

    rules, messages = parse_lines(lines)
    if part == 1
        day19_part1(rules, messages)
    elseif part == 2
        day19_part2(rules, messages)
    end
end

function parse_lines(lines::Vector{String})
    rules = Dict{Int, Rule}()
    i = 1
    while !isempty(lines[i])
        id, rule = parse_rule(lines[i])
        rules[id] = rule
        i += 1
    end

    messages = lines[(i+1):end]
    return rules, messages
end

function parse_rule(line::String)
    parts = split(line, ": ")
    id = parse(Int, parts[1])
    rule_str = parts[2]
    if rule_str[1] == '"'
        char = rule_str[2]
        return id, Rule(id, [], char)
    else
        subrules = [parse.(Int, split(s)) for s in split(rule_str, " | ")]
        return id, Rule(id, subrules, nothing)
    end
end

function day19_part1(rules::Dict{Int, Rule}, messages::Vector{String})
    valid_strings = enumerate_rule(rules, 0)
    result = count(msg -> msg in valid_strings, messages)
    println("Answer: $result")
end

function day19_part2(rules::Dict{Int, Rule}, messages::Vector{String})
    # Modify rules 8 and 11
    modified_rule_8 = Rule(8, [[42], [42, 8]], nothing)
    rules[8] = modified_rule_8
    modified_rule_11 = Rule(11, [[42, 31], [42, 11, 31]], nothing)
    rules[11] = modified_rule_11

    # Enumerate the possible strings for rules 42 and 31
    enumerated_rule_42 = enumerate_rule(rules, 42)
    enumerated_rule_31 = enumerate_rule(rules, 31)

    # This only works if all strings generated by rules 42 and 31 are the same length
    @assert all(length(s) == length(enumerated_rule_42[1]) for s in enumerated_rule_42)
    @assert all(length(s) == length(enumerated_rule_31[1]) for s in enumerated_rule_31)
    @assert length(enumerated_rule_42[1]) == length(enumerated_rule_31[1])
    chunk_length = length(enumerated_rule_42[1])

    valid_count = 0
    for message in messages
        # Key idea: A valid message consists of 2 or more instances of rule 42 followed by 1 or more instances of rule 31

        i = 1
        n_rule42_chunks = 0
        n_rule31_chunks = 0

        # Consume chunks of rule 42
        while any(startswith(message[i:end], rule42_chunk) for rule42_chunk in enumerated_rule_42)
            i += chunk_length
            n_rule42_chunks += 1
        end

        # If fewer than 2 chunks of rule 42 were found or only rule 42 chunks were found, this message cannot be valid
        if i < 1 + 2 * chunk_length || i > length(message)
            continue
        end

        # Consume chunks of rule 31
        while any(startswith(message[i:end], rule31_chunk) for rule31_chunk in enumerated_rule_31)
            i += chunk_length
            n_rule31_chunks += 1
        end

        # A valid message must have more rule 42 chunks than rule 31 chunks
        if n_rule42_chunks <= n_rule31_chunks
            continue
        end

        # If we have consumed the entire message, it is valid
        if i > length(message)
            valid_count += 1
        end
    end

    println("Answer: $(valid_count)")
end

function enumerate_rule(rules::Dict{Int, Rule}, id::Int)
    enumerations = String[]
    rule = rules[id]
    if rule.char !== nothing
        push!(enumerations, string(rule.char))
    else
        for subrule in rule.subrules
            sub_enumerations = [""]
            for sub_id in subrule
                sub_rule_enums = enumerate_rule(rules, sub_id)
                sub_enumerations = [s * t for s in sub_enumerations, t in sub_rule_enums]
            end
            append!(enumerations, sub_enumerations)
        end
    end
    return enumerations
end

export day19

end
